# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 166529ea7b09ddc45ab380261733442f28d3bfb863173080295a8926b0e5d894129ffb7b9eaafd09bb32dd9caa7e8baef1835b0663f6b194688e4622e27e5b76

test:
  secret_key_base: 08fece27b80f0719763350728221aa1b7ad6dfb9a26959ef4fe6868f60de95a489741695b5e2f1465ba047e1b2bebb01af779d42499f36bc102726432aaa5d91

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
